### ISSUE TITLE
Virus'

### ISSUE THREAD

**Issue by The-Royal-Cunt** [blackrosezy/build-libboost-windows#1]
cp.exe  
Antivirus   Result  Update
TheHacker   Posible_Worm32  20140929
TrendMicro  PAK_Generic.005 20140930
TrendMicro-HouseCall    PAK_Generic.005 20140930

check the rest at https://www.virustotal.com/en/

**Comment by blackrosezy** [comment]
Thank you for your report. Unfortunately this is false alarm. All the *.exe was packed using the UPX packer - http://upx.sourceforge.net/ (to reduce file size) and somehow Virustotal treat it as virus.

All the *.exe have now been replaced with the original one.

**Comment by The-Royal-Cunt** [comment]
I am not so sure I swear by Virus Total and I think they learn it can
happen just with a simple network hack . Check your enemy list cant fight
that 57 virus scanners wont find if it's there ... .
